<!DOCTYPE html>
<html>
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="/generated/css/home.css">

    <script type="text/javascript" data-main="/generated/js/main.js" src="/generated/js/require.js"></script>

</head>


$common/header()$        


<div class="container">

    <body>
      $page/home()$         
    </body>

</div>


$common/footer()$


</html>